---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    ignore:
      - dependency-name: "*"
      - update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "*"
      - update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    ignore:
      - dependency-name: "*"
      - update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
